APP_ENV=feature
PROJECT_SLUG=csda-studio-app

DATABASE_ENGINE=postgres
DATABASE_IMAGE=postgres:16
DATABASE_HOST=db
DATABASE_PORT=5433
DATABASE_CONTAINER_PORT=5432
DATABASE_NAME=csda_studio_app_feature
DATABASE_USER=csda_studio_app_app
DATABASE_PASSWORD=change-me
DATABASE_URL=postgresql://csda_studio_app_app:change-me@db:5432/csda_studio_app_feature

POSTGRES_DB=csda_studio_app_feature
POSTGRES_USER=csda_studio_app_app
POSTGRES_PASSWORD=change-me
